[username]
style_user = "bright-white"
style_root = "red"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname](bright-white) "
trim_at = "."
disabled = false

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

[directory]
read_only = " "
format = '[in ](red)[$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = true
use_os_path_sep = false
style = "italic bright-white"

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "italic red"

[shell]
disabled = true

[aws]
symbol = "  "

[azure]
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue'

[docker_context]
symbol = " "
format = "[via ](bright-white)[$symbol$context]($style) "
style = "bright-blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "red"

[git_status]
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
staged = '[+${count} ](green)'
untracked = '[?${count} ](white)'
stashed = '[\$${count} ](bright-yellow)'
modified = '[*${count} ](yellow)'
renamed = '[»${count} ](blue)'
conflicted = '󰓥${count} '
deleted = '[${count} ](bright-red)'
format = '[$all_status$ahead_behind]($style)'

[dotnet]
detect_extensions = ['sln', 'csproj', 'fsproj', 'xproj']

[golang]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
format = '[via ](bright-white)[${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bright-blue"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[lua]
symbol = " "
style = 'blue'

[terraform]
symbol = "󱁢 "

[nodejs]
format = "[via ](bright-white)[${symbol}Node.js $version](bright-blue) "
