[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/stuff/"
desc = "Go stuff"

[[mgr.prepend_keymap]]
on = ["g", "n"]
run = "cd ~/stuff/knowtes/"
desc = "Go Obsidian knowtes"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = "cd ~/stuff/repo/"
desc = "Go repo"

[[mgr.prepend_keymap]]
on = ["g", "."]
run = "cd ~/stuff/repo/.dotfiles/"
desc = "Go dotfiles"

[[mgr.prepend_keymap]]
on = ["g", "a"]
run = "cd /games/"
desc = "Go games"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd ~/stuff/movies/"
desc = "Go movies"

[[mgr.prepend_keymap]]
on = ["g", "/"]
run = "cd /"
desc = "Go root"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "Open lazygit"

[[mgr.prepend_keymap]]
on = ["i", "d"]
run = "plugin disk-info"
desc = "Info: disk usage"

[[mgr.prepend_keymap]]
on = ["i", "f"]
run = "plugin file-info"
desc = "Info: file"

[[mgr.prepend_keymap]]
on = ["i", "s"]
run = "plugin system-info"
desc = "Info: system"

[[mgr.prepend_keymap]]
on = ["e", "a"]
run = 'shell --orphan "aseprite %h"'
desc = "Edit in Aseprite"

[[mgr.prepend_keymap]]
on = ["e", "g"]
run = 'shell --orphan "gimp %h"'
desc = "Edit in GIMP"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Open file or enter directory"

[[mgr.prepend_keymap]]
on = "t"
run = "plugin tab-hover"
desc = "New tab at hovered directory"

[[mgr.prepend_keymap]]
on = "J"
run = "arrow 50%"
desc = "Half page down"

[[mgr.prepend_keymap]]
on = "K"
run = "arrow -50%"
desc = "Half page up"
